name: version up npm
on:
  workflow_dispatch:
    inputs:
      releaseSize:
        description: 'release size'
        required: true
        default: 'patch'
        type: choice
        options:
          - 'patch'
          - 'minor'
          - 'major'

jobs:
  versionUp:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: cat package
        run: cat ./package.json
      - name: Git config
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
      - name: version up and push tag
        run: | 
          npm version ${{ github.event.inputs.releaseSize }}
          git add package.json
          git push --follow-tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create a GitHub release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          release_name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
          draft: true
          prerelease: false