name: version up npm
on:
  workflow_dispatch:
    inputs:
      releaseSize:
        description: 'release size'
        required: true
        default: 'patch'
        type: choice
        options:
          - 'patch'
          - 'minor'
          - 'major'

jobs:
  versionUp:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: cat version
        run: npm version
      - name: Git config
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
      - name: version up and push tag
        run: | 
          npm version ${{ github.event.inputs.releaseSize }} --no-git-tag-version
          git add package.json
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: cat version
        run: npm version
